name: Azure Static Web Apps CI/CD (OIDC)

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job (OIDC)
    permissions:
       id-token: write
       contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build app
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web App (OIDC)
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"
          skip_api_build: true
          output_location: "dist"
